version: "3.8"

services:
  api:
    build:
      context: ./bunpj
      dockerfile: ../docker/Dockerfile
    image: caddy-gateway-api:latest
    labels:
      - "virtual.host=${VIRTUAL_HOST}"
      - "virtual.port=${API_PORT}"
      - "virtual.tls=${TLS_MODE}"
      - "auth.validatejwt=${AUTH_VALIDATE_JWT}"
      - "auth.server=${SSO_AUTH_SERVER}"
      - "auth.realm=${SSO_REALM}"
      - "auth.clientid=${SSO_CLIENTID}"
    env_file:
      - ./.env
    volumes:
      - ./bunpj:/app
      - /app/node_modules

networks:
  default:
    name: proxy-network
    external: true
