version: "3.8"

services:
  api:
    build:
      context: ./api
      dockerfile: ../docker/Dockerfile
    container_name: api-service
    image: caddy-gateway-api:latest
    labels:
      - "virtual.host=api.shopsthai.com"
      - "virtual.port=3000"
      - "virtual.tls=internal"
      - "auth.validatejwt=true"
      - "auth.server=sso.shopsthai.com"
      - "auth.realm=shopsthai.app"
      - "auth.clientid=shopsthai-api"
    env_file:
      - ./api/.env
    environment:
      - NODE_ENV=production
      - TZ=Asia/Bangkok

networks:
  default:
    external:
      name: proxy-network
